services:
  - type: web
    name: todo_django
    env: python
    plan: free
    buildCommand: |
      pip install --upgrade pip
      pip install -r requirements.txt
      python manage.py makemigrations
      python manage.py migrate
      python manage.py collectstatic --noinput
    startCommand: gunicorn todo.wsgi:application --bind 0.0.0.0:$PORT
    envVars:
      - key: DEBUG
        value: "True"
      - key: SECRET_KEY
        generateValue: true
      - key: PYTHON_VERSION
        value: 3.14.0